name: valorant_client
description: Library to interact with Riot's Valorant Game API.
version: 1.1.4
homepage: https://github.com/ArunPrakashG/valorant_client
repository: https://github.com/ArunPrakashG/valorant_client

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2

dependencies:
  cookie_jar: ^3.0.1
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0

assets:
  - "assets/test.json"
